# These are the configuration options available to the user in the UI on the Service page, under 'Config.'
# See github.com/Start9Labs/lnd-wrapper for a good example config_spec


disable-metrics:
  type: boolean
  name: Disable Server Metrics
  description: Disable metrics reporting to serverMonitor.txt and associated tracking routines
  changeWarning: Disabling server metrics reporting will prevent data from being saved to serverMonitor.txt and associated tracking routines
  default: true

# POTENTIAL BUG: I'm not sure if this is actually being recognized by Cwtch and disabling the metrics reporting. Still needs to be tested properly. 